version: "0.3"
services:
  
  api:
    build: ./api 
    ports:
        - "43451:43451"
    depends_on:
        - mongodb
    networks:
        - app-net

  fastapi:
    build: ./fastapi
    ports:
        - "33333:33333"
    depends_on:
        - mongodb
    networks:
        - app-net
    environment:
        - MONGO_URI=mongodb://mongodb:27017
    volumes:
        - ./fastapi:/app

  mongodb:
    image: mongo:latest
    ports:
        - "27017:27017"
    networks:
        - app-net

volumes:
    fastapi:
        external: false
    mongodb:
        external: false

networks:
  app-net:
    driver: bridge
  
